.github/CODEOWNERS

Remove CODEOWNER file
This file is not needed (at least for now) in this project

🔥 remove CODEOWNER file

---

src/components/WalletConnect/index.tsx

Support `eth_sign` and `eth_signTypedData` for https://ledgerhq.atlassian.net/browse/LIVE-4378

feat: add eth_sign & eth_signTypedData support

---

src/components/WalletConnect/Disconnected.tsx

The Vault QA team would need to have UI items with a `data-test` attribute, so they can target them in their automated tests suite

VG-11281 add data-test attributes to some UI items for testing

---

src/components/WalletConnect/index.tsx

Fix issue : [SignTypedData](https://github.com/LedgerHQ/wallet-connect-live-app/issues/55)

🐛 Fix Issue SignTyped Data

---

public/locales/en/common.json
src/components/WalletConnect/index.tsx
src/pages/index.tsx

[LIVE-6714](https://ledgerhq.atlassian.net/browse/LIVE-6714)
https://user-images.githubusercontent.com/112866305/226867038-09419b51-8a16-4ce4-8452-9647db474c73.mov
[LIVE-6714]: https://ledgerhq.atlassian.net/browse/LIVE-6714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add account button when no account is found

---

src/pages/detail.tsx

[LIVE-6843](https://ledgerhq.atlassian.net/browse/LIVE-6843)
[LIVE-6843]: https://ledgerhq.atlassian.net/browse/LIVE-6843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix wrong account display if Eth and Polygon have same adressé

---

src/components/WalletConnect/Connected.tsx
src/components/WalletConnect/PendingRequest.tsx

We need to automate some actions on the WC iframe for test purposes.
We already have the data-test for some buttons but it was missing for 'Disconnect' 'Switch account', 'Decline' and 'Connect'

Add data test

---

src/hooks/useWalletConnectEventsManager.ts

Update made like the [https://github.com/LedgerHQ/eth-dapp-browser/blob/main/src/DAPPBrowserV2/Player.tsx#L414](solution)

bugfix(API): new format on sign message handled

---

.gitignore
next.config.js
package.json
sentry.client.config.ts
sentry.edge.config.ts
sentry.server.config.ts
src/components/screens/Home.tsx
src/components/screens/QRScanner.tsx
src/components/screens/sessions/Sessions.tsx
src/hooks/useInitialization.ts
src/hooks/useProposal.ts
src/hooks/useWalletConnectEventsManager.ts
src/pages/detail.tsx
src/pages/index.tsx
src/pages/proposal.tsx
src/shared/helpers/converters.ts
src/shared/helpers/walletConnect.util.ts
src/storage/pendingFlow.store.ts
yarn.lock

**This PR fixes the issue that was causing some swap transactions to lose their `data` field resulting in users losing funds**
Introduced on June 30 2023 by [this commit](https://github.com/LedgerHQ/wallet-connect-live-app/commit/6a1e0df8681d66c5c2fcf526dca37497b0cb30ee) (here is the [JIRA ticket](https://ledgerhq.atlassian.net/browse/LIVE-8531))
**Reasons for the pendingFlow :**
When we are connected to a dapp (paraswap for example) and we trigger an operation (either a sign message or a transaction) some dapp send the information of the operation to the wallet connect live app that then triggers the appropriate flow on Ledger Live. However some dapp also triggers a deeplink that opens Ledger Live and redirects to the live app which causes it to refresh and it reinitializes the transport …

Wallet connect swap transactions fixed

---

public/locales/en/common.json
src/components/screens/Connect.tsx
src/components/screens/Home.tsx
src/hooks/common/useNavigation.ts
src/pages/protocol-not-supported.tsx
src/pages/protocol.tsx

FEAT: Add V1 Error Screen

---

README.md
src/data/network.config.ts
src/data/types.d.ts
src/pages/detail.tsx
src/pages/proposal.tsx
src/shared/helpers/__tests__/helper.util.test.ts
src/shared/helpers/helper.util.ts

[SUPPORT] : colors on icons 💄

---

src/__tests__/integrations/networkSupport.integration.test.tsx
src/__tests__/integrations/proposal.integration.test.tsx
src/components/screens/Home.tsx
src/components/screens/sessions/Sessions.tsx
src/data/network.config.ts
src/hooks/common/useNavigation.ts
src/hooks/useProposal.ts
src/hooks/useWalletConnectEventsManager.ts
src/pages/detail.tsx
src/shared/navigation.ts

> [!NOTE]
> Replace the hook enum with one exported from an appended file, so you don't have to redefine enums in tests

🛠  [SUPPORT] Update navigation files

---

README.md
package.json
src/__tests__/integrations/networkSupport.integration.test.tsx
src/__tests__/units/addAccountPlaceholder.test.tsx
src/components/atoms/logoContainers/DAppLogoContainer.tsx
src/components/atoms/logoContainers/LedgerLogoContainer.tsx
src/components/atoms/popin/WalletConnectPopin.tsx
src/hooks/common/useLedgerLive.ts
src/hooks/useInitialization.ts
src/hooks/useProposal.ts
src/pages/detail.tsx
src/pages/index.tsx
src/pages/proposal.tsx
src/pages/protocol-not-supported.tsx
src/shared/helpers/__tests__/generic.test.ts
src/shared/helpers/generic.ts
src/shared/helpers/helper.util.ts
src/shared/helpers/walletConnect.util.ts
tsconfig.json

Update & Improve some parts of Code

🛠 Few updates & improvments

---

jest.config.js

Update coverage collect rules to remove unnecessary files.
Not sure about why pages were excluded.

Update coverage collect rules

---

.github/workflows/code-coverage.yml
sonar-project.properties

Add SonarQube Analysis in the project

🛠  [SUPPORT] : Add SonarQube

---

.github/workflows/code-coverage.yml

As we checkout twice we are losing coverage results I think.
https://sonarcloud.io/summary/new_code?id=ledger_wallet-connect-live-app&pullRequest=123

Update CI to not checkout twice the branch

---

jest.config.js
src/__tests__/units/porotocol-not-supported.test.tsx
src/__tests__/units/protocol-not-supported.test.tsx

[TEST] : Increase coverage

---

localManifest.json
src/data/network.config.ts

Add new support for **Base** 
- Mainnet
- Goerli
https://base.org/
------
DEMO 🚀 
on MAC
https://github.com/LedgerHQ/wallet-connect-live-app/assets/112866305/2622d027-2b5e-4424-abee-5e0da6d2569f
https://github.com/LedgerHQ/wallet-connect-live-app/assets/112866305/eb940e82-8f3c-4c2a-93ff-f9fd01a2980e
on LLM
https://github.com/LedgerHQ/wallet-connect-live-app/assets/112866305/0ba7046f-5276-44ff-aa3f-cac24c440862
https://github.com/LedgerHQ/wallet-connect-live-app/assets/112866305/c1a58fe7-2887-448c-8030-7bb34a121ed6
Tx :
[transaction](https://etherscan.io/tx/0x31292342eb0f8cf2199d20a513f3376d0129a7b836f0db2538c015f84d1186d0)

🛠  [SUPPORT]: Add Base Mainnet & Goerli support

---

README.md

Add supported Currencies in README

[SUPPORT] : Update Readme with currencies

---

src/components/atoms/images/ImageWithPlaceholder.tsx
src/components/screens/sessions/Sessions.tsx
src/pages/detail.tsx
src/pages/proposal.tsx
src/shared/helpers/__tests__/image.test.ts
src/shared/helpers/helper.util.ts
src/shared/helpers/image.ts

decodeURI when giving html instead of string
- https://github.com/safe-global/safe-wallet-web/issues/2538
https://github.com/LedgerHQ/wallet-connect-live-app/assets/112866305/b58101bf-3f37-4775-b13a-5a190c4ebc8f

[BUGFIX] : decodeURI when giving html instead of string

---

.github/workflows/assigner.yml
.github/workflows/checks.yml
.github/workflows/code-coverage.yml
.github/workflows/stale.yml

[SUPPORT] : Update Workflows CI

---

src/__tests__/integrations/proposal.integration.test.tsx
src/components/screens/Home.tsx
src/components/screens/index.tsx
src/pages/_app.tsx
src/pages/detail.tsx
src/pages/index.tsx
src/pages/proposal.tsx
src/shared/WalletApiClientProvider.ts
src/storage/__tests__/sessions.store.test.ts
src/storage/sessions.store.ts

Reworked the initialization of wallet connect. The createWeb3Wallet function was called on every page instead of once at the load of the App.
This may have been the cause of most of the `Keychain not found` errors and this PR may fix them.
- **Linked resource(s)**: [LIVE-9420] 
[LIVE-9420]: https://ledgerhq.atlassian.net/browse/LIVE-9420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

⚡ Reworked the initialization of wallet connect

---

package.json
yarn.lock

Upgrade newest version of Jest

[SUPPORT] : Upgrade Jest ⬆️

---

src/hooks/__tests__/useProposal.test.ts
src/hooks/useProposal/useProposal.ts
src/hooks/useProposal/util.ts
src/pages/proposal.tsx

Sort Chains during proposal : 
1.  Required (Sorted Alphabetically) 
2. Chains with Accounts (Sorted Alphabetically) 
3. Chains without Account (Sorted Alphabetically) 
**BEFORE** 
**AFTER**

[FEAT]: Sort Chains during proposal

---

src/components/screens/ApplicationDisabled.tsx
src/components/screens/Connect.tsx
src/components/screens/Home.tsx
src/components/screens/errors/errorFallback.tsx
src/components/screens/index.tsx
src/components/screens/sessions/Sessions.tsx
src/components/screens/sessions/sessionProposal/AddAccountPlaceholder.tsx
src/hooks/useProposal/useProposal.ts
src/hooks/useWalletConnectEventsManager.ts
src/hooks/useWalletConnectPopin.ts
src/pages/detail.tsx

PR improving performance and general usage of WalletConnect : 
- Remove useless `useCallback` and `useEffect`
- Clean some unused `const` and `variables`

[SUPPORT] : Improve performances and UX ⚡️

---

.gitignore
next.config.js

Try to enable more stack trace when error on Sentry 

[SUPPORT]: Try upload source maps to Sentry

---

src/hooks/useWalletConnectEventsManager.ts
src/shared/types/types.ts

sign_transaction handler should not broadcast the transaction
- **Linked resource(s)**: [LIVE-10985]
[LIVE-10985]: https://ledgerhq.atlassian.net/browse/LIVE-10985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: sign_transaction handler should not broadcast

---

src/components/screens/Connect.tsx
src/components/screens/Sessions.tsx

- **Linked resource(s)**: https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/issues/LIVE-11492?jql=project%20%3D%20%22LIVE%22%20ORDER%20BY%20created%20DESC

fix: quick wins

---

localManifest.json
src/components/screens/SessionDetail.tsx
src/data/methods/MultiversX.methods.ts
src/data/network.config.ts
src/hooks/useProposal/useProposal.ts
src/hooks/useProposal/util.ts
src/hooks/useWalletConnect.ts
src/utils/converters.ts
src/utils/helper.util.ts

feat: support multivers x

---

src/hooks/useProposal/useProposal.ts

check for chains in optional namespaces

---

src/components/atoms/Notification.tsx

Right now, toast can block / hide critical action when trying to connect. 
https://github.com/LedgerHQ/wallet-connect-live-app/assets/5050709/645bf5d6-fad0-4119-8b0c-eeb27912c668
This is a quick fix but further work should be put into this (dismiss button, cross icon ?) 
For now, clicking on the toast makes it go away 

dismiss toast on click

---

src/components/screens/SessionProposal.tsx

- **Linked resource(s)**: LIVE-12230
https://github.com/LedgerHQ/wallet-connect-live-app/assets/5050709/2c27b887-2fab-462a-83a7-18e5d0f258bd

LIVE-12230 enforce at least one account is selected

---

src/components/atoms/GenericRow.tsx
src/components/screens/SessionDetail.tsx
src/components/screens/sessionProposal/AccountRow.tsx
src/hooks/useProposal/useProposal.ts

display error toast on request account error

---

localManifest.json
src/components/atoms/AccountBalance.tsx
src/components/atoms/GenericRow.tsx
src/components/atoms/containers/Elements.tsx
src/components/screens/SessionDetail.tsx
src/components/screens/SessionProposal.tsx
src/components/screens/sessionProposal/AccountRow.tsx
src/data/methods/BIP122.methods.ts
src/data/network.config.ts
src/hooks/useProposal/useProposal.ts
src/hooks/useWalletConnect.ts
src/store/wallet-api.store.ts
src/utils/__tests__/helper.util.test.ts
src/utils/helper.util.ts

Add support for BTC, TBTC, LTC and DOGE signMessage
You can test locally with this version of the test example dApp from wallet-connect web-examples repo: https://github.com/Justkant/web-examples/tree/feature/bip122 
- **Linked resource(s)**: [LIVE-11978] and [LIVE-11982]
[LIVE-11978]: https://ledgerhq.atlassian.net/browse/LIVE-11978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-11982]: https://ledgerhq.atlassian.net/browse/LIVE-11982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add support for btc, ltc and doge signMessage [LIVE-11978]

---

public/locales/ar-AE/common.json
public/locales/de-DE/common.json
public/locales/es-ES/common.json
public/locales/fr-FR/common.json
public/locales/ja-JP/common.json
public/locales/ko-KR/common.json
public/locales/pt-BR/common.json
public/locales/ru-RU/common.json
public/locales/tr-TR/common.json
public/locales/zh-CN/common.json

Please review this translation file update. Changes in the source file have been applied. The relevant Smartling translation job may be empty - https://dashboard.smartling.com/app/accounts/d32c14dd/account-jobs/046061cb7:qntdnlggr5by

Smartling translations are updated for PR#168 from feat/relayer-connection-indicator

---

public/locales/ar-AE/common.json
public/locales/de-DE/common.json

Please review this translation pull request. The relevant Smartling translation job is available here - https://dashboard.smartling.com/app/accounts/d32c14dd/account-jobs/046061cb7:skxerm30qfar
Here is a link to the source commit which triggered translation - https://github.com/LedgerHQ/wallet-connect-live-app/commit/275b37bd4f41b654a725b187658b20fd7f99572a

Smartling translations are completed for commit 275b37bd4f41b654a725b187658b20fd7f99572a from main

---

localManifest.json
src/components/screens/SessionDetail.tsx
src/data/methods/Ripple.methods.ts
src/data/network.config.ts
src/hooks/useProposal/useProposal.ts
src/hooks/useProposal/util.ts
src/hooks/useWalletConnect.ts
src/utils/converters.ts
src/utils/helper.util.ts
vite.config.ts

feat: add ripple support

---

public/locales/en/common.json
src/components/ProposalRow.tsx
src/components/atoms/GenericRow.tsx
src/components/screens/SessionDetail.tsx
src/components/screens/SessionProposal.tsx
src/components/screens/Sessions.tsx
src/components/screens/sessionProposal/AccountRow.tsx
src/components/verification/VerificationCard.tsx
src/components/verification/VerificationLabel.tsx
src/hooks/useProposal/useProposal.ts
src/hooks/useVerification.ts
src/hooks/useWalletConnect.ts
src/types/types.ts

Flag malicious websites by 
[TICKET](https://ledgerhq.atlassian.net/browse/LIVE-13642) 
scam: 
unkown or no validation: 
invalid: 
valid: 
mobile: 
proposal list

Flag malicious websites

---

README.md
localManifest.json
src/data/methods/EIP155Data.methods.ts
src/data/methods/Wallet.methods.ts
src/data/network.config.ts
src/hooks/requestHandlers/BIP122.ts
src/hooks/requestHandlers/EIP155.ts
src/hooks/requestHandlers/MultiversX.ts
src/hooks/requestHandlers/Ripple.ts
src/hooks/requestHandlers/Wallet.ts
src/hooks/requestHandlers/utils.ts
src/hooks/useProposal/useProposal.ts
src/hooks/useWalletConnect.ts
src/utils/helper.util.ts

Support switch chains in live-app
Refactor session_request handling in multiple files
Fix proposal accept with mixed required and optional namespaces
Correctly invalidate session cache when finish with a session_request in case of changes
- **Linked resource(s)**: [LIVE-13659]
[LIVE-13659]: https://ledgerhq.atlassian.net/browse/LIVE-13659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: support switch chains [LIVE-13659]

---

README.md
localManifest.json
src/data/__tests__/networkConfig.test.ts
src/data/network.config.ts

This PR adds rootstock chain to the list of supported networks in wallet-connect-live-app. 
About Rootstock
Website: https://rootstock.io/
Defillama: https://defillama.com/chain/Rootstock
Explorer: https://explorer.rootstock.io/
Developer portal: https://dev.rootstock.io/
We are working on to enable wallet connect via ledger for Rootstock in https://github.com/LedgerHQ/ledger-live. For that, purpose we need this PR to be merged so that we can add support for Rootstock in ledger-live for wallet connect.

Add `Rootstock` chain

---

src/components/screens/SessionProposal.tsx

Improve blur with linear gradient
| Before | 
|:-:|
| <img width="1107" alt="Screenshot 2024-11-04 at 15 22 37" src="https://github.com/user-attachments/assets/7148c608-c181-4117-91c8-5fc6a332ef59"> |
| After |
| <img width="1031" alt="Screenshot 2024-11-04 at 13 21 20" src="https://github.com/user-attachments/assets/878724dd-29f1-413d-85e6-b0dff8b16415"> |

fix: improve blur

---

src/hooks/requestHandlers/Wallet.ts
src/hooks/useProposal/useProposal.ts

Select added accounts on proposal screen

feat: select added accounts on proposal screen

---

src/components/screens/SessionProposal.tsx

Reject is sometimes not clearly visible, so we want to fix that.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-17974
| Before  | After  |
| -------- | -------- |
|  <img width="713" alt="image" src="https://github.com/user-attachments/assets/808eea43-f229-4a46-aea2-e8f88bdeac57" />  |  <img width="725" alt="image" src="https://github.com/user-attachments/assets/a3c2b16b-1729-4741-8a0e-20e1e01fda96" />  |

fix reject button visibility

---

package.json
patches/react-qr-reader.patch
pnpm-lock.yaml

Patching the base lib to select the last device in the list as it should be the standard camera in most cases
Dirty solution until we can select the device in the UI
- **Linked resource(s)**: [LIVE-17967]
[LIVE-17967]: https://ledgerhq.atlassian.net/browse/LIVE-17967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: qr reader multi camera selection [LIVE-17967]

---

src/components/screens/RecentlyUsedApps.tsx
src/components/screens/Sessions.tsx
src/components/screens/SuggestedApps.tsx

Increase font size for two messages on the live app (all translations)
- **Linked resource(s)**: [LIVE-17872](https://ledgerhq.atlassian.net/browse/LIVE-17872?atlOrigin=eyJpIjoiNDA0OTMyYWM1NTUzNDRhMzlhNzRiYTdmNWQ2ZjMzMWMiLCJwIjoiaiJ9)
[LIVE-17872]: https://ledgerhq.atlassian.net/browse/LIVE-17872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Displaying issue on 1 Thai sentence on LLM/LLD

---

localManifest.json
src/data/network.config.ts

Fixing wrong currency id used for testnet and devnet of solana

fix: wrong currency id for solana testnet and devnet

---

src/data/network.config.ts
src/hooks/requestHandlers/Wallet.ts
src/hooks/useSupportedNamespaces.ts
src/hooks/useWalletConnect.ts

fix: disable xrpl temporarily
